### ISSUE TITLE
Using the <!--more--> tag causes incorrect read times to display

### ISSUE THREAD

**Issue by johnalarcon** [azurecurve/Estimated-Read-Time#3]
HT to @azurecurve for reporting the following unexpected behavior.

> If I have a &lt;!--more--> in a post, the read time on the homepage or archive is only for the bit above the &lt;!--more--> When you open the post, the read time is different as it is for the whole post.

**A few things to verify and work out:**
* The post/page and excerpts should show total read time, regardless of &lt;!--more--> tags. Verify that this expected behavior exists.
* Any pages auto-created with a &lt;!--more--> tag should have the full post's read time displayed. Verify the issue.

**Possible Solutions**
1. Show full read time on all displays (ie, the extra pages generated by &lt;!--more-->)
1. Show read time of current auto-page as something like `4-mins of a 23-minute read`.

I like the _idea_ of the second solution, but, feel it's too verbose for the purpose. The first solution seems more viable. I'll leave this open a bit to gather any feedback before implementing the fix.

**Comment by azurecurve** [comment]
I think only solution 1 is viable; showing the read time of the shown element is pretty much useless; if I only see the two hundred words of a two thousand word article, how does knowing the first bit takes 1 minute to read? I need to know how long the whole article will take before I start.

p.s. your description is hiding the &#60;!--more--&#62; tag due to the chevrons

**Comment by johnalarcon** [comment]
I tend to agree.

Thanks for the heads up on the chevrons - fixed.

**Comment by johnalarcon** [comment]
In testing the `<--more-->` tag, I realize that I've _assumed_ what it does rather than actually _knowing_. My assumption was that adding the `<!--more-->` tag to a post was a way to divide it up unto a series of pages. Like... a few paragraphs, then the tag, then a few more paragraphs, then the tag...would create a paginated article. Not true. This tag is an alternative to using core excerpts.

**Comment by johnalarcon** [comment]
Using `$post->post_content` instead of `get_the_content()` in the shortcode resolves this issue. The [documentation ](https://github.com/johnalarcon/estimated-read-time )has been updated to reflect this finding. The following code blocks demonstrate the change.

**Previous Shortcode**
`<?php echo do_shortcode('[estimated-read-time words="'.str_word_count(strip_tags( get_the_content() )).'"]'); ?>`

**Updated Shortcode**
`<?php echo do_shortcode('[estimated-read-time words="'.str_word_count(strip_tags( $post->post_content )).'"]'); ?>`

**Comment by azurecurve** [comment]
> ...My assumption was that adding the `<!--more-->` tag to a post was a way to divide it up unto a series of pages...
The tag for that is &lt;!--nextpage--&gt;

**Comment by johnalarcon** [comment]
Nice, thanks for confirming.
